#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    conf.define('ISIX_CONFIG_SHUTDOWN_API',1)
    conf.define( 'ISIX_CONFIG_USE_TIMERS', 1 )


def build(bld):
    src = bld.path.ant_glob( '*.cpp' )
    src += bld.path.ant_glob( '*.S' )
    bld.program(
            features='objcopy',
            target='fatsdio',
            source=src,
            install_path=False,
            includes=[ '.' ],
            use=[ 'foundation', 'isix', 'stm32', 'fatfs', 'isixdrvstm32' ]
            )
