#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    conf.define('ISIX_CONFIG_SHUTDOWN_API',1)


def build(bld):
    src = bld.path.ant_glob( '*.cpp' )
    bld.program(
            features='objcopy',
            target='fatsdio',
            source=src,
            install_path=False,
            includes=[ 'include' ],
            use=[ 'foundation', 'isix', 'stm32', 'fatfs' ]
            )
