#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    conf.define('CONFIG_ISIX_SHUTDOWN_API',1)


def build(bld):
    src = bld.path.ant_glob( '*.cpp' )
    src += bld.path.ant_glob( '*.S' )
    bld.program(
            features='objcopy',
            target='fpuctx',
            source=src,
            install_path=False,
            includes=[ '.' ],
            use=[ 'foundation', 'isix', 'stm32' ]
            )
