#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    import os
    stdinc = os.path.join(conf.path.abspath(),'include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.check_cxx( header_name='isix_config.h', features='cxx',
            define_name='HAVE_ISIX_CONFIG_H' )
    conf.define('CONFIG_ISIX_SHUTDOWN_API',1)


def build(bld):
    src = bld.path.ant_glob( '*.cpp' )
    src += bld.path.ant_glob( '*.S' )
    bld.program(
            features='objcopy',
            target='fpuctx',
            source=src,
            install_path=False,
            includes=[ '.' ],
            use=[ 'foundation', 'isix', 'stm32' ]
            )
