#!/usr/bin/env python

import os

def options(opt):
    pass

def configure(conf):
    stdinc = os.path.join(conf.path.abspath(),'board','include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.check_cxx( header_name='isix_config.h', features='cxx',
            define_name='HAVE_ISIX_CONFIG_H' )
    conf.env.ISIX_COMPILE_TCPIP_DRIVERS=True


def build(bld):
    src = bld.path.ant_glob( '**/*.cpp' )
    src += bld.path.ant_glob( '**/*.c' )
    bld.program(
            features='objcopy',
            target='test334',
            source=src,
            install_path=False,
            includes=[ '.', 'board/include' ],
            use=[ 'isix', 'stm32', 'foundation' ]
            )

