#!/usr/bin/env python

import os

_libs = [
    'isixrtos/libisixdrvstm32'
]

def options(opt):
    pass

def configure(conf):
    stdinc = os.path.join(conf.path.abspath(),'board','include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.check_cxx( header_name='isix_config.h', features='cxx',
            define_name='HAVE_ISIX_CONFIG_H' )
    for lib in _libs:
        conf.recurse( os.path.join(os.getcwd(),lib) )


def build(bld):
    for lib in _libs:
        bld.recurse( os.path.join(os.getcwd(),lib) )
    src = bld.path.ant_glob( '**/*.cpp' )
    src += bld.path.ant_glob( '**/*.c' )
    bld.program(
            features='objcopy',
            target='test334',
            source=src,
            install_path=False,
            includes=[ '.', 'board/include' ],
            use=[ 'isix', 'stm32', 'foundation', 'isixdrvstm32' ]
            )

