#!/usr/bin/env python

import platform

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.program(
            features='objcopy',
            target='example1',
            source=bld.path.ant_glob( '*.c' ),
            includes='.',
            use=[ 'foundation', 'isix', 'stm32', 'startup' ],
            )



