#!/usr/bin/env python


def options(opt):
    pass

def configure(conf):
    import os
    stdinc = os.path.join(conf.path.abspath(),'include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.env.LDFLAGS += [ '-Wl,--undefined=_external_startup' ]

def build(bld):
    src = bld.path.ant_glob( '*.c' )
    src += bld.path.ant_glob( '*.cpp' )
    inc = ['./include' ]
    bld.stlib( source=src,
            includes = inc, export_includes=inc,
            target='stm32f411ed_boot', use= ['isix', 'periph','common_conf']
    )

