#!/usr/bin/env python

# Example waf script for BF700 reference isix boards

# Projects list
_prjs = [
    'components_demo'
]

#Additional extra libraries
_libs = [
    'bf700/board',
    'isixrtos/libgfx',
    'isixrtos/libtcpip',
]

import os

# Configure
def configure( cfg ):
    cfg.define('CONFIG_GFX_PIXEL_FORMAT', 1 )
    for lib in _libs:
        cfg.recurse( os.path.join(os.getcwd(),lib) )
    cfg.recurse( _prjs )


# Build
def build( bld ):
    for lib in _libs:
        bld.recurse( os.path.join(os.getcwd(),lib) )
    bld.recurse( _prjs )

