all:
	$(MAKE) -C example1
	$(MAKE) -C example2
	$(MAKE) -C example3
	$(MAKE) -C example4
	$(MAKE) -C example_exceptions

clean:
	$(MAKE) -C example1 clean
	$(MAKE) -C example2 clean
	$(MAKE) -C example3 clean
	$(MAKE) -C example4 clean
	$(MAKE) -C example_exceptions clean


