#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    conf.define('CONFIG_ISIX_SHUTDOWN_API',1)
    conf.define( 'CONFIG_ISIX_USE_TIMERS', 1 )
    import os
    stdinc = os.path.join(conf.path.abspath(),'include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.check_cxx( header_name='isix_config.h', features='cxx',
            define_name='HAVE_ISIX_CONFIG_H' )


def build(bld):
    src = bld.path.ant_glob( '*.cpp' )
    src += bld.path.ant_glob( '*.S' )
    bld.program(
            features='objcopy',
            target='fatsdio',
            source=src,
            install_path=False,
            includes=[ '.' ],
            use=[ 'foundation', 'isix', 'stm32', 'fatfs', 'isixdrvstm32' ]
            )
