#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    import os
    stdinc = os.path.join(conf.path.abspath(),'include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.check_cxx( header_name='config.h', features='cxx',
            define_name='_HAVE_CONFIG_H' )
    conf.define('CONFIG_ISIX_SHUTDOWN_API',1)
    conf.ISIX_COMPILE_TCPIP_DRIVERS = True


def build(bld):
    src = bld.path.ant_glob( '**/*.cpp' )
    src = bld.path.ant_glob( '**/*.c' )
    bld.program(
            features='objcopy',
            target='tcpdemo',
            source=src,
            install_path=False,
            includes=[ 'include' ],
            use=[ 'foundation', 'isix', 'stm32', 'isixdrvstm32', 'tcpip' ]
            )
