#!/usr/bin/env python

# List of examples for old board KAMAMI stm32Butterfly
# This board is not longer manufactured by Kamami

# Projects list
_prjs = [
    'envfs',
    'fatsdio',
    'gfxdemo',
    'isix_c_examples',
    'isix_cpp_examples'
    #'tcpdemo',
    #'usbhostkbd'
]

#Additional extra libraries
_libs = [
    'isixrtos/libisixdrvstm32',
    'isixrtos/libgfx',
    'isixrtos/libfsfat',
    #'isixrtos/libtcpip',
    #'isixrtos/libusb',
    'isixrtos/libfsfat',
]

import os

# Configure
def configure( cfg ):
    cfg.define( 'CONFIG_ISIX_TASK_STACK_CHECK', 1 )
    for lib in _libs:
        cfg.recurse( os.path.join(os.getcwd(),lib) )
    cfg.recurse( _prjs )


# Build
def build( bld ):
    for lib in _libs:
        bld.recurse( os.path.join(os.getcwd(),lib) )
    bld.recurse( _prjs )

