#!/usr/bin/env python

# Example waf script for ZL41ARM Kamami board

# Projects list
_prjs = [
    'blink',
    'dacaudio',
    'fatsdio',
    'fpuctx',
    'mpudemo'
]

#Additional extra libraries
_libs = [
    'isixrtos/libisixdrvstm32',
    'isixrtos/libfsfat',
]

import os

# Configure
def configure( cfg ):
    for lib in _libs:
        cfg.recurse( os.path.join(os.getcwd(),lib) )
    cfg.recurse( _prjs )


# Build
def build( bld ):
    for lib in _libs:
        bld.recurse( os.path.join(os.getcwd(),lib) )
    bld.recurse( _prjs )

