#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    conf.define('CONFIG_ISIX_SHUTDOWN_API',1)
    conf.define( 'CONFIG_ISIX_USE_TIMERS', 1 )


def build(bld):
    src = bld.path.ant_glob( '*.cpp' )
    bld.program(
            features='objcopy',
            target='blink',
            source=src,
            install_path=False,
            includes=[ 'include' ],
            use=[ 'foundation', 'isix', 'stm32', 'graphics' ]
            )
