#!/usr/bin/env python

import platform

bld_subdirs = [
    'example1',
]

def options(opt):
    opt.recurse( bld_subdirs )


def configure(conf):
    conf.recurse( bld_subdirs )

def build(bld):
    bld.recurse( bld_subdirs )


