#!/usr/bin/env python

import os

def options(opt):
    pass

#TODO: Fixme that crap related to the HAVE_CONFIG_H
def configure(conf):
    stdinc = os.path.join(conf.path.abspath(),'board','include')
    conf.env.append_value('INCLUDES', stdinc )
    conf.check_cxx( header_name='config.h', features='cxx',
            define_name='_HAVE_CONFIG_H' )
    conf.define( 'WITH_ISIX_TCPIP_LIB' , 1 )


def build(bld):
    src = bld.path.ant_glob( '**/*.cpp' )
    src += bld.path.ant_glob( '**/*.c' )
    bld.program(
            features='objcopy',
            target='brefboard',
            source=src,
            includes=[ '.', 'board/include' ],
            use=[ 'foundation', 'isix', 'stm32',
                'isixdrvstm32', 'graphics', 'fatfs', 'tcpip' ]
            )
