#!/usr/bin/env python

import os

def options(opt):
    pass


def configure(conf):
    conf.check(fragment='int main() { return 0; }\n')
    #conf.define( '_HAVE_CONFIG_H', 1 )


def build(bld):
    src = bld.path.ant_glob( '**/*.cpp' )
    src += bld.path.ant_glob( '**/*.c' )
    bld.program(
            features='objcopy',
            target='brefboard',
            source=src,
            includes=[ '.', 'board/include' ],
            use=[ 'foundation', 'isix', 'stm32',
                'isixdrvstm32', 'graphics', 'fatfs' ]
            )
