#!/usr/bin/env python

# Example waf script for STM32F411 discovery

# Projects list
_prjs = [
    'e0_led_blink',
    'e1_mutex',
    'e2_task_suspend',
    'e3_semaphore',
    'e4_fifo_from_irq',
    'e5_events',
    'e6_spi_mems',
    'e7_i2c_mems'
]

#Additional extra libraries
_libs = [
    'stm32f411e_disco/board'
]

import os

# Configure
def configure( cfg ):
    for lib in _libs:
        cfg.recurse( os.path.join(os.getcwd(),lib) )
    cfg.recurse( _prjs )


# Build
def build( bld ):
    for lib in _libs:
        bld.recurse( os.path.join(os.getcwd(),lib) )
    bld.recurse( _prjs )
