#!/usr/bin/env python

# Example waf script for STM32F411 discovery

# Projects list
_prjs = [
    'led_blink'
]

#Additional extra libraries
_libs = [
    
]

import os

# Configure
def configure( cfg ):
    for lib in _libs:
        cfg.recurse( os.path.join(os.getcwd(),lib) )
    cfg.recurse( _prjs )


# Build
def build( bld ):
    for lib in _libs:
        bld.recurse( os.path.join(os.getcwd(),lib) )
    bld.recurse( _prjs )
